services:
  # PostgreSQL Database
  - type: pserv
    name: medilog-database
    databaseName: medilog
    user: medilog_user
    plan: free

  # Web Service
  - type: web
    name: medilog-backend
    runtime: docker
    repo: https://github.com/akash20122001/medilog-backend.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medilog-database
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: medilog-database
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: medilog-database
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080